### ISSUE TITLE
Encode exception when email contains only attachments and no text or html body

### ISSUE THREAD

**Issue by clambert-daileycomputer** [cnicodeme/mailparse#3]
Exception is thrown when the email has not text or html body and only attachments.

Adding this check avoids the exception:
```
if msg['text'] is None and msg['html'] is None:
        msg['text'] = 'Empty Message Body'
```

My code using bytes fed from python's email module:
```
def encode_email(file_bytes, filename):
    msg = EmailDecode.load(file_bytes)
    if msg['text'] is None and msg['html'] is None:
        msg['text'] = 'Empty Message Body'
    with open('new_file.eml', 'wb') as w:
        w.write(bytes(EmailEncode(msg)))
```

The exception:
```
Traceback (most recent call last):
  File "/home/cameron/git/Barracuda-Message-Archiver-150-Data-Extractor/decode_barracuda.py", line 45, in <module>
    reencode_email('/home/cameron/Documents/New Folder/extracted/working_folder/34/d/e6/extracting/c5fc6372586c360860e39ba9a5d6f')
  File "/home/cameron/git/Barracuda-Message-Archiver-150-Data-Extractor/decode_barracuda.py", line 42, in reencode_email
    encode_email(new_py_email.as_bytes(), filename)
  File "/home/cameron/git/Barracuda-Message-Archiver-150-Data-Extractor/decode_barracuda.py", line 16, in encode_email
    w.write(bytes(EmailEncode(f)))
                  ^^^^^^^^^^^^^^
  File "/home/cameron/.conda/envs/bextract/lib/python3.12/site-packages/mailparse/encoder.py", line 99, in __init__
    mixed.attach(parent)
                 ^^^^^^
UnboundLocalError: cannot access local variable 'parent' where it is not associated with a value
```

**Comment by cnicodeme** [comment]
Thank you for submitting this issue!

I created a fake email with just an attachment and got no issues trying to convert it back to EML.

Could you provide an EML sample that causes this bug ?

Here's my sample:

```eml
Content-Type: multipart/mixed; boundary="===============6138355785717050547=="
MIME-Version: 1.0
From: sender@domain.com
To: receiver@domain.net
Date: Wed, 31 Jan 2024 11:37:24 +0100
Subject: This is a test

--===============6138355785717050547==
Content-Type: application/octet-stream
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=empty.zip

UEsFBgAAAAAAAAAAAAAAAAAAAAAAAA==

--===============6138355785717050547==--
```

With the following test code:

```python

with open('file.eml', 'rb') as f:
    data = f.read()

eml = EmailDecode.load(data)
print(str(EmailEncode(eml))

# Works with too
print(bytes(EmailEncode(eml)))
```

There must be some specific structure on your file that causes the bug.

Thank you.
